import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://chindatsyzvaieflwzlf.supabase.co'
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoaW5kYXRzeXp2YWllZmx3emxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyMTQyNDcsImV4cCI6MjA5MDc5MDI0N30.wXR9NpRmeRGNQxBUM3156-qiQD27flejhHUI0Mr3jq0'

export const supabase = createClient(supabaseUrl, supabaseAnonKey)

export const supabaseAdmin = createClient(
  supabaseUrl,
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoaW5kYXRzeXp2YWllZmx3emxmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NTIxNDI0NywiZXhwIjoyMDkwNzkwMjQ3fQ.8kxEYnXcqEfzeWIv948SlWxR-iHggXImwtDtsJb6T-Q'
)
